import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { defaultLocale } from '@/middleware'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: {lang: string};
}) {
  return (
    <html lang={params.lang ?? defaultLocale}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
